CREATE DATABASE Lab5
GO
USE Lab5
GO

DROP TABLE IF EXISTS Ta 
CREATE TABLE Ta(
	aid INT PRIMARY KEY IDENTITY(1,1),
	a2 INT UNIQUE);

DROP TABLE IF EXISTS Tb 
CREATE TABLE Tb(
	bid INT PRIMARY KEY IDENTITY(1,1),
	b2 INT );

DROP TABLE IF EXISTS Tc 
CREATE TABLE Tc(
	cid INT PRIMARY KEY IDENTITY(1,1),
	aid INT FOREIGN KEY REFERENCES Ta(aid),
	bid INT FOREIGN KEY REFERENCES Tb(bid));


INSERT INTO Ta VALUES (-11), (0), (7), (99)
INSERT INTO Tb VALUES (1), (1), (15), (7), (2)
INSERT INTO Tc VALUES (1,2), (2,4), (3,5)

SELECT * FROM Ta 
SELECT * FROM Tb
SELECT * FROM Tc 


SELECT * FROM sys.indexes

IF EXISTS(SELECT name FROM sys.indexes WHERE name = 'N_Tb_b2_')
DROP INDEX N_Tb_b2 ON Tb;

CREATE NONCLUSTERED INDEX N_Tb_b2 ON Tb(b2)
GO

--CLUSTERED INDEX SCAN
SELECT * FROM Tb ORDER BY bid 

--CLUSTERED INDEX SEEK
SELECT * FROM Ta WHERE aid>0

--NON CLUSTERED INDEX SCAN AND KEY LOOKUP
SELECT * FROM Tb ORDER BY b2 

--NON CLUSTERED INDEX SEEK
SELECT * FROM Ta  WHERE a2=7  --0032831

--B)
SELECT * FROM Tb WHERE b2=1  --0032842

--C)
GO
CREATE VIEW cVIEW
AS
	SELECT * FROM Ta a
	INNER JOIN Tb b ON a.a2=b.b2
GO 

SELECT * FROM cVIEW 
